### ISSUE TITLE
Super F4 softlocks when used on desktop.

### ISSUE THREAD

**Issue by L0ST5ILVER** [stefansundin/superf4#13]
When you press Ctrl + alt + F4 on the desktop the entire screen goes black, you can still do things like Alt + TAB to resume other windows, and Ctrl + Alt + Del to open task manager, and it appears; but everything on the desktop just goes pure black, then having to restart the computer to fix it.

**Comment by L0ST5ILVER** [comment]
And before someone says "don't use it on the desktop then"
This is actually not as simple as that, as some applications randomly "unselect" not sure if that's the right work, but basically going from being highlighted, to not highlighted.
Like this: Highlighted - http://prntscr.com/ft06jz None highlighted - http://prntscr.com/ft06np
Sometimes applications/executable do this meaning when you press Ctrl + Alt + F4 it softlocks the desktop.
It's basically a problem which is uncommon, but not rare by any means.

**Comment by camperboy1000** [comment]
Don't use it on the desktop then! JK
Instead of restarting the computer, you can just open task manager, click "File", "run new task", and in the "run" box type "explorer". Your explorer should come right back along with your desktop. You can't press Win + R and open a run box because that is managed by Windows Explorer, which is killed when you kill the desktop.

**Comment by L0ST5ILVER** [comment]
Thanks!
Regards,
**-L0ST**

**Comment by stefansundin** [comment]
The new version today has a process blacklist, with `explorer.exe` in it by default. Hopefully that resolves this issue. https://github.com/stefansundin/superf4/releases/tag/v1.4
