### ISSUE TITLE
Uninstall tries to uninstall WINrar

### ISSUE THREAD

**Issue by TheAFKGamer10** [stefansundin/superf4#53]
When I try to uninstall SuperF4 via the win11 menu, it thinks i am trying to uninstall WinRAR and pops-up with the uninstall confirmation.  Win11 also says that it takes up 210Gb or storage that is way i am trying to uninstall it. Any recommendations on why this is happening?

**Comment by pzhlkj6612** [comment]
Hi. Maybe you had accidentally installed SuperF4 into the WinRAR's directory or vice versa? I guess re-installing both the two software with carefully (to overwrite Registry entries) may solve your problem.

**Comment by stefansundin** [comment]
Hello,

That is very strange, I've never heard of this happening before.

The installer computes the size of the directory, so _probably_ you installed it in an existing directory that was already very large. 🤔 

So perhaps you installed SuperF4 in the WinRAR directory.. Or maybe you installed WinRAR in the SuperF4 directory?

https://github.com/stefansundin/superf4/blob/6b677d422553e6b908b9eeaff4333b8b457e7bef/installer.nsi#L177-L180

Anyway.. more information would be helpful. If you know how to use the registry editor (`regedit.exe`) then you can go to `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\SuperF4` and take a screenshot like this:

![Uninstall-regedit](https://github.com/stefansundin/superf4/assets/1991151/c98da9b9-a1a1-46d2-9677-454b379165c1)

`EstimatedSize` is what the installer calculates and writes there which is what the "Apps & Features" program displays as the program size.

P.S. I don't use Windows 11 yet so I don't know if there's any discrepancies because of that.

**Comment by TheAFKGamer10** [comment]
That was why i was breaking, because I had it installed in my Downloads folder and not in a separate one just for the app. Thanks for the solution.

**Comment by stefansundin** [comment]
Thanks for figuring that out. 👍 

The portable zip file may suit your preferences better than the installer.
